const items = [
  { id: "voc-abecedario", name: "El abecedario", emoji: "🔠", words: [
      { word: "a", img: "img/El abecedario/a.jpg" },
      { word: "be", img: "img/El abecedario/be.jpg" },
      { word: "ce", img: "img/El abecedario/ce.jpg" },
      { word: "de", img: "img/El abecedario/de.jpg" },
      { word: "e", img: "img/El abecedario/e.jpg" },
      { word: "efe", img: "img/El abecedario/efe.jpg" },
      { word: "ge", img: "img/El abecedario/ge.jpg" },
      { word: "hache", img: "img/El abecedario/hache.jpg" },
      { word: "i", img: "img/El abecedario/i.jpg" },
      { word: "jota", img: "img/El abecedario/jota.jpg" },
      { word: "ka", img: "img/El abecedario/ka.jpg" },
      { word: "ele", img: "img/El abecedario/ele.jpg" },
      { word: "eme", img: "img/El abecedario/eme.jpg" },
      { word: "ene", img: "img/El abecedario/ene.jpg" },
      { word: "eñe", img: "img/El abecedario/eñe.jpg" },
      { word: "o", img: "img/El abecedario/o.jpg" },
      { word: "pe", img: "img/El abecedario/pe.jpg" },
      { word: "cu", img: "img/El abecedario/cu.jpg" },
      { word: "erre", img: "img/El abecedario/erre.jpg" },
      { word: "ese", img: "img/El abecedario/ese.jpg" },
      { word: "te", img: "img/El abecedario/te.jpg" },
      { word: "u", img: "img/El abecedario/u.jpg" },
      { word: "uve", img: "img/El abecedario/uve.jpg" },
      { word: "uve doble", img: "img/El abecedario/uve doble.jpg" },
      { word: "equis", img: "img/El abecedario/equis.jpg" },
      { word: "igrega", img: "img/El abecedario/igrega.jpg" },
      { word: "zeta", img: "img/El abecedario/zeta.jpg" },
      { word: "che", img: "img/El abecedario/che.jpg" },
      { word: "elle", img: "img/El abecedario/elle.jpg" },
    ]},
{
  id: "voc-ropa",
  name: "La ropa",
  emoji: "👕",
  words: [
    { word: "El abrigo", img: "img/La ropa/El abrigo.jpg", transcript: "[el aˈβɾiɣo]" },
    { word: "El jersey", img: "img/La ropa/El jersey.jpg", transcript: "[el xeɾˈsej]" },
    { word: "El traje", img: "img/La ropa/El traje.jpg", transcript: "[el ˈtɾaxe]" },
    { word: "La camisa", img: "img/La ropa/La camisa.jpg", transcript: "[la kaˈmisa]" },
    { word: "El vestido", img: "img/La ropa/El vestido.jpg", transcript: "[el besˈtiðo]" },
    { word: "La camiseta", img: "img/La ropa/La camiseta.jpg", transcript: "[la kamiˈseta]" },
    { word: "La chaqueta", img: "img/La ropa/La chaqueta.jpg", transcript: "[la tʃaˈketa]" },
    { word: "La pijama", img: "img/La ropa/La pijama.jpg", transcript: "[la piˈxama]" },
    { word: "La falda", img: "img/La ropa/La falda.jpg", transcript: "[la ˈfalda]" },
    { word: "Los pantalones cortos", img: "img/La ropa/Los pantalones cortos.jpg", transcript: "[los pantaˈlones ˈkoɾtos]" },
    { word: "Los vaqueros", img: "img/La ropa/Los vaqueros.jpg", transcript: "[los baˈkeɾos]" },
    { word: "Los pantalones", img: "img/La ropa/Los pantalones.jpg", transcript: "[los pantaˈlones]" }
  ]
},
{
  id: "voc-frutas",
  name: "Las frutas",
  emoji: "🍎",
  words: [
    { word: "Las frutas", img: "img/Las frutas/Las frutas.jpg", transcript: "[las ˈfɾutas]" },
    { word: "La uva", img: "img/Las frutas/La uva.jpg", transcript: "[la ˈuβa]" },
    { word: "La pera", img: "img/Las frutas/La pera.jpg", transcript: "[la ˈpeɾa]" },
    { word: "La granada", img: "img/Las frutas/La granada.jpg", transcript: "[la gɾaˈnaða]" },
    { word: "La ciruela", img: "img/Las frutas/La ciruela.jpg", transcript: "[la θiɾweˈla]" },
    { word: "El plátano", img: "img/Las frutas/El plátano.jpg", transcript: "[el ˈplatano]" },
    { word: "El coco", img: "img/Las frutas/El coco.jpg", transcript: "[el ˈkoko]" },
    { word: "El albaricoque", img: "img/Las frutas/El albaricoque.jpg", transcript: "[el alβaɾiˈkoke]" },
    { word: "La piña", img: "img/Las frutas/La piña.jpg", transcript: "[la ˈpiɲa]" },
    { word: "El caqui", img: "img/Las frutas/El caqui.jpg", transcript: "[el ˈkaki]" },
    { word: "El kiwi", img: "img/Las frutas/El kiwi.jpg", transcript: "[el ˈkiwi]" },
    { word: "El limón", img: "img/Las frutas/El limón.jpg", transcript: "[el liˈmon]" },
    { word: "El mango", img: "img/Las frutas/El mango.jpg", transcript: "[el ˈmango]" },
    { word: "El melocotón", img: "img/Las frutas/El melocotón.jpg", transcript: "[el meloˌkotoˈn]" },
    { word: "El pomelo", img: "img/Las frutas/El pomelo.jpg", transcript: "[el poˈmelo]" },
    { word: "La lima", img: "img/Las frutas/La lima.jpg", transcript: "[la ˈlima]" },
    { word: "La manzana", img: "img/Las frutas/La manzana.jpg", transcript: "[la manˈθana]" },
    { word: "La naranja", img: "img/Las frutas/La naranja.jpg", transcript: "[la naˈɾanxa]" }
  ]
},
{
  id: "voc-números",
  name: "Los números de 0 a 100",
  emoji: "🔢",
  words: [
    { word: "Cero", img: "img/Los números/Cero.jpg", transcript: "[ˈθeɾo]" },
    { word: "Uno", img: "img/Los números/Uno.jpg", transcript: "[ˈuno]" },
    { word: "Dos", img: "img/Los números/Dos.jpg", transcript: "[dos]" },
    { word: "Tres", img: "img/Los números/Tres.jpg", transcript: "[tɾes]" },
    { word: "Cuatro", img: "img/Los números/Cuatro.jpg", transcript: "[ˈkwatɾo]" },
    { word: "Cinco", img: "img/Los números/Cinco.jpg", transcript: "[ˈθiŋko]" },
    { word: "Seis", img: "img/Los números/Seis.jpg", transcript: "[sejs]" },
    { word: "Siete", img: "img/Los números/Siete.jpg", transcript: "[ˈsjete]" },
    { word: "Ocho", img: "img/Los números/Ocho.jpg", transcript: "[ˈotʃo]" },
    { word: "Nueve", img: "img/Los números/Nueve.jpg", transcript: "[ˈnweβe]" },
    { word: "Diez", img: "img/Los números/Diez.jpg", transcript: "[djes]" },
    { word: "Once", img: "img/Los números/Once.jpg", transcript: "[ˈonθe]" },
    { word: "Doce", img: "img/Los números/Doce.jpg", transcript: "[ˈdoθe]" },
    { word: "Trece", img: "img/Los números/Trece.jpg", transcript: "[ˈtɾeθe]" },
    { word: "Catorce", img: "img/Los números/Catorce.jpg", transcript: "[kaˈtoɾθe]" },
    { word: "Quince", img: "img/Los números/Quince.jpg", transcript: "[ˈkinθe]" },
    { word: "Dieciséis", img: "img/Los números/Dieciséis.jpg", transcript: "[djeθiˈsejs]" },
    { word: "Diecisiete", img: "img/Los números/Diecisiete.jpg", transcript: "[djeθiˈsjete]" },
    { word: "Dieciocho", img: "img/Los números/Dieciocho.jpg", transcript: "[djeθiˈotʃo]" },
    { word: "Diecinueve", img: "img/Los números/Diecinueve.jpg", transcript: "[djeθiˈnweβe]" },
    { word: "Veinte", img: "img/Los números/Veinte.jpg", transcript: "[ˈbejnte]" },
    { word: "Veintiuno", img: "img/Los números/Veintiuno.jpg", transcript: "[bejntiˈuno]" },
    { word: "Veintidós", img: "img/Los números/Veintidós.jpg", transcript: "[bejntiˈdos]" },
    { word: "Veintitrés", img: "img/Los números/Veintitrés.jpg", transcript: "[bejntiˈtɾes]" },
    { word: "Veinticuatro", img: "img/Los números/Veinticuatro.jpg", transcript: "[bejntiˈkwatɾo]" },
    { word: "Veinticinco", img: "img/Los números/Veinticinco.jpg", transcript: "[bejntiˈθiŋko]" },
    { word: "Veintiséis", img: "img/Los números/Veintiséis.jpg", transcript: "[bejntiˈsejs]" },
    { word: "Veintisiete", img: "img/Los números/Veintisiete.jpg", transcript: "[bejntiˈsjete]" },
    { word: "Veintiocho", img: "img/Los números/Veintiocho.jpg", transcript: "[bejntiˈotʃo]" },
    { word: "Veintinueve", img: "img/Los números/Veintinueve.jpg", transcript: "[bejntiˈnweβe]" },
    { word: "Treinta", img: "img/Los números/Treinta.jpg", transcript: "[ˈtɾejnta]" },
    { word: "Treinta y uno", img: "img/Los números/Treinta y uno.jpg", transcript: "[ˈtɾejnta i ˈuno]" },
    { word: "Treinta y dos", img: "img/Los números/Treinta y dos.jpg", transcript: "[ˈtɾejnta i ˈdos]" },
    { word: "Treinta y tres", img: "img/Los números/Treinta y tres.jpg", transcript: "[ˈtɾejnta i ˈtɾes]" },
    { word: "Treinta y cuatro", img: "img/Los números/Treinta y cuatro.jpg", transcript: "[ˈtɾejnta i ˈkwatɾo]" },
    { word: "Treinta y cinco", img: "img/Los números/Treinta y cinco.jpg", transcript: "[ˈtɾejnta i ˈθiŋko]" },
    { word: "Treinta y seis", img: "img/Los números/Treinta y seis.jpg", transcript: "[ˈtɾejnta i ˈsejs]" },
    { word: "Treinta y siete", img: "img/Los números/Treinta y siete.jpg", transcript: "[ˈtɾejnta i ˈsjete]" },
    { word: "Treinta y ocho", img: "img/Los números/Treinta y ocho.jpg", transcript: "[ˈtɾejnta i ˈotʃo]" },
    { word: "Treinta y nueve", img: "img/Los números/Treinta y nueve.jpg", transcript: "[ˈtɾejnta i ˈnweβe]" },
    { word: "Cuarenta", img: "img/Los números/Cuarenta.jpg", transcript: "[kwaˈɾenta]" },
    { word: "Cuarenta y uno", img: "img/Los números/Cuarenta y uno.jpg", transcript: "[kwaˈɾenta i ˈuno]" },
    { word: "Cuarenta y dos", img: "img/Los números/Cuarenta y dos.jpg", transcript: "[kwaˈɾenta i ˈdos]" },
    { word: "Cuarenta y tres", img: "img/Los números/Cuarenta y tres.jpg", transcript: "[kwaˈɾenta i ˈtɾes]" },
    { word: "Cuarenta y cuatro", img: "img/Los números/Cuarenta y cuatro.jpg", transcript: "[kwaˈɾenta i ˈkwatɾo]" },
    { word: "Cuarenta y cinco", img: "img/Los números/Cuarenta y cinco.jpg", transcript: "[kwaˈɾenta i ˈθiŋko]" },
    { word: "Cuarenta y seis", img: "img/Los números/Cuarenta y seis.jpg", transcript: "[kwaˈɾenta i ˈsejs]" },
    { word: "Cuarenta y siete", img: "img/Los números/Cuarenta y siete.jpg", transcript: "[kwaˈɾenta i ˈsjete]" },
    { word: "Cuarenta y ocho", img: "img/Los números/Cuarenta y ocho.jpg", transcript: "[kwaˈɾenta i ˈotʃo]" },
    { word: "Cuarenta y nueve", img: "img/Los números/Cuarenta y nueve.jpg", transcript: "[kwaˈɾenta i ˈnweβe]" },
    { word: "Cincuenta", img: "img/Los números/Cincuenta.jpg", transcript: "[θinˈkwenta]" },
    { word: "Cincuenta y uno", img: "img/Los números/Cincuenta y uno.jpg", transcript: "[θinˈkwenta i ˈuno]" },
    { word: "Cincuenta y dos", img: "img/Los números/Cincuenta y dos.jpg", transcript: "[θinˈkwenta i ˈdos]" },
    { word: "Cincuenta y tres", img: "img/Los números/Cincuenta y tres.jpg", transcript: "[θinˈkwenta i ˈtɾes]" },
    { word: "Cincuenta y cuatro", img: "img/Los números/Cincuenta y cuatro.jpg", transcript: "[θinˈkwenta i ˈkwatɾo]" },
    { word: "Cincuenta y cinco", img: "img/Los números/Cincuenta y cinco.jpg", transcript: "[θinˈkwenta i ˈθiŋko]" },
    { word: "Cincuenta y seis", img: "img/Los números/Cincuenta y seis.jpg", transcript: "[θinˈkwenta i ˈsejs]" },
    { word: "Cincuenta y siete", img: "img/Los números/Cincuenta y siete.jpg", transcript: "[θinˈkwenta i ˈsjete]" },
    { word: "Cincuenta y ocho", img: "img/Los números/Cincuenta y ocho.jpg", transcript: "[θinˈkwenta i ˈotʃo]" },
    { word: "Cincuenta y nueve", img: "img/Los números/Cincuenta y nueve.jpg", transcript: "[θinˈkwenta i ˈnweβe]" },
    { word: "Sesenta", img: "img/Los números/Sesenta.jpg", transcript: "[seˈsenta]" },
    { word: "Sesenta y uno", img: "img/Los números/Sesenta y uno.jpg", transcript: "[seˈsenta i ˈuno]" },
    { word: "Sesenta y dos", img: "img/Los números/Sesenta y dos.jpg", transcript: "[seˈsenta i ˈdos]" },
    { word: "Sesenta y tres", img: "img/Los números/Sesenta y tres.jpg", transcript: "[seˈsenta i ˈtɾes]" },
    { word: "Sesenta y cuatro", img: "img/Los números/Sesenta y cuatro.jpg", transcript: "[seˈsenta i ˈkwatɾo]" },
    { word: "Sesenta y cinco", img: "img/Los números/Sesenta y cinco.jpg", transcript: "[seˈsenta i ˈθiŋko]" },
    { word: "Sesenta y seis", img: "img/Los números/Sesenta y seis.jpg", transcript: "[seˈsenta i ˈsejs]" },
    { word: "Sesenta y siete", img: "img/Los números/Sesenta y siete.jpg", transcript: "[seˈsenta i ˈsjete]" },
    { word: "Sesenta y ocho", img: "img/Los números/Sesenta y ocho.jpg", transcript: "[seˈsenta i ˈotʃo]" },
    { word: "Sesenta y nueve", img: "img/Los números/Sesenta y nueve.jpg", transcript: "[seˈsenta i ˈnweβe]" },
    { word: "Setenta", img: "img/Los números/Setenta.jpg", transcript: "[seˈtenta]" },
    { word: "Setenta y uno", img: "img/Los números/Setenta y uno.jpg", transcript: "[seˈtenta i ˈuno]" },
    { word: "Setenta y dos", img: "img/Los números/Setenta y dos.jpg", transcript: "[seˈtenta i ˈdos]" },
    { word: "Setenta y tres", img: "img/Los números/Setenta y tres.jpg", transcript: "[seˈtenta i ˈtɾes]" },
    { word: "Setenta y cuatro", img: "img/Los números/Setenta y cuatro.jpg", transcript: "[seˈtenta i ˈkwatɾo]" },
    { word: "Setenta y cinco", img: "img/Los números/Setenta y cinco.jpg", transcript: "[seˈtenta i ˈθiŋko]" },
    { word: "Setenta y seis", img: "img/Los números/Setenta y seis.jpg", transcript: "[seˈtenta i ˈsejs]" },
    { word: "Setenta y siete", img: "img/Los números/Setenta y siete.jpg", transcript: "[seˈtenta i ˈsjete]" },
    { word: "Setenta y ocho", img: "img/Los números/Setenta y ocho.jpg", transcript: "[seˈtenta i ˈotʃo]" },
    { word: "Setenta y nueve", img: "img/Los números/Setenta y nueve.jpg", transcript: "[seˈtenta i ˈnweβe]" },
    { word: "Ochenta", img: "img/Los números/Ochenta.jpg", transcript: "[oˈtʃenta]" },
    { word: "Ochenta y uno", img: "img/Los números/Ochenta y uno.jpg", transcript: "[oˈtʃenta i ˈuno]" },
    { word: "Ochenta y dos", img: "img/Los números/Ochenta y dos.jpg", transcript: "[oˈtʃenta i ˈdos]" },
    { word: "Ochenta y tres", img: "img/Los números/Ochenta y tres.jpg", transcript: "[oˈtʃenta i ˈtɾes]" },
    { word: "Ochenta y cuatro", img: "img/Los números/Ochenta y cuatro.jpg", transcript: "[oˈtʃenta i ˈkwatɾo]" },
    { word: "Ochenta y cinco", img: "img/Los números/Ochenta y cinco.jpg", transcript: "[oˈtʃenta i ˈθiŋko]" },
    { word: "Ochenta y seis", img: "img/Los números/Ochenta y seis.jpg", transcript: "[oˈtʃenta i ˈsejs]" },
    { word: "Ochenta y siete", img: "img/Los números/Ochenta y siete.jpg", transcript: "[oˈtʃenta i ˈsjete]" },
    { word: "Ochenta y ocho", img: "img/Los números/Ochenta y ocho.jpg", transcript: "[oˈtʃenta i ˈotʃo]" },
    { word: "Ochenta y nueve", img: "img/Los números/Ochenta y nueve.jpg", transcript: "[oˈtʃenta i ˈnweβe]" },
    { word: "Noventa", img: "img/Los números/Noventa.jpg", transcript: "[noˈβenta]" },
    { word: "Noventa y uno", img: "img/Los números/Noventa y uno.jpg", transcript: "[noˈβenta i ˈuno]" },
    { word: "Noventa y dos", img: "img/Los números/Noventa y dos.jpg", transcript: "[noˈβenta i ˈdos]" },
    { word: "Noventa y tres", img: "img/Los números/Noventa y tres.jpg", transcript: "[noˈβenta i ˈtɾes]" },
    { word: "Noventa y cuatro", img: "img/Los números/Noventa y cuatro.jpg", transcript: "[noˈβenta i ˈkwatɾo]" },
    { word: "Noventa y cinco", img: "img/Los números/Noventa y cinco.jpg", transcript: "[noˈβenta i ˈθiŋko]" },
    { word: "Noventa y seis", img: "img/Los números/Noventa y seis.jpg", transcript: "[noˈβenta i ˈsejs]" },
    { word: "Noventa y siete", img: "img/Los números/Noventa y siete.jpg", transcript: "[noˈβenta i ˈsjete]" },
    { word: "Noventa y ocho", img: "img/Los números/Noventa y ocho.jpg", transcript: "[noˈβenta i ˈotʃo]" },
    { word: "Noventa y nueve", img: "img/Los números/Noventa y nueve.jpg", transcript: "[noˈβenta i ˈnweβe]" },
    { word: "Cien", img: "img/Los números/Cien.jpg", transcript: "[θjen]" }
  ]
},
{
  "id": "voc-números-grande",
  "name": "Los números desde 100",
  "emoji": "💯",
  "words": [
    { "word": "Cien", "img": "img/Los números/Cien.jpg", "transcript": "[θjen]" },
    { "word": "Ciento uno", "img": "img/Los números/Ciento uno.jpg", "transcript": "[ˈθjento ˈuno]" },
    { "word": "Ciento once", "img": "img/Los números/Ciento once.jpg", "transcript": "[ˈθjento ˈonθe]" },
    { "word": "Doscientos", "img": "img/Los números/Doscientos.jpg", "transcript": "[dosˈθjentos]" },
    { "word": "Doscientos dos", "img": "img/Los números/Doscientos dos.jpg", "transcript": "[dosˈθjentos dos]" },
    { "word": "Doscientos veintidós", "img": "img/Los números/Doscientos veintidós.jpg", "transcript": "[dosˈθjentos bejntiˈdos]" },
    { "word": "Trescientos", "img": "img/Los números/Trescientos.jpg", "transcript": "[tɾesˈθjentos]" },
    { "word": "Trescientos tres", "img": "img/Los números/Trescientos tres.jpg", "transcript": "[tɾesˈθjentos tɾes]" },
    { "word": "Trescientos treinta y tres", "img": "img/Los números/Trescientos treinta y tres.jpg", "transcript": "[tɾesˈθjentos ˈtɾejnta i ˈtɾes]" },
    { "word": "Cuatrocientos", "img": "img/Los números/Cuatrocientos.jpg", "transcript": "[kwatɾoˈθjentos]" },
    { "word": "Cuatrocientos cuatro", "img": "img/Los números/Cuatrocientos cuatro.jpg", "transcript": "[kwatɾoˈθjentos ˈkwatɾo]" },
    { "word": "Cuatrocientos cuarenta y cuatro", "img": "img/Los números/Cuatrocientos cuarenta y cuatro.jpg", "transcript": "[kwatɾoˈθjentos kwaˈɾenta i ˈkwatɾo]" },
    { "word": "Quinientos", "img": "img/Los números/Quinientos.jpg", "transcript": "[kinˈθjentos]" },
    { "word": "Quinientos cinco", "img": "img/Los números/Quinientos cinco.jpg", "transcript": "[kinˈθjentos ˈθinko]" },
    { "word": "Quinientos cincuenta y cinco", "img": "img/Los números/Quinientos cincuenta y cinco.jpg", "transcript": "[kinˈθjentos θinˈkwenta i ˈθinko]" },
    { "word": "Seiscientos", "img": "img/Los números/Seiscientos.jpg", "transcript": "[sejˈθjentos]" },
    { "word": "Seiscientos seis", "img": "img/Los números/Seiscientos seis.jpg", "transcript": "[sejˈθjentos sejs]" },
    { "word": "Seiscientos sesenta y seis", "img": "img/Los números/Seiscientos sesenta y seis.jpg", "transcript": "[sejˈθjentos seˈsenta i ˈsejs]" },
    { "word": "Setecientos", "img": "img/Los números/Setecientos.jpg", "transcript": "[seteˈθjentos]" },
    { "word": "Setecientos siete", "img": "img/Los números/Setecientos siete.jpg", "transcript": "[seteˈθjentos ˈsjete]" },
    { "word": "Setecientos setenta y siete", "img": "img/Los números/Setecientos setenta y siete.jpg", "transcript": "[seteˈθjentos seˈtenta i ˈsjete]" },
    { "word": "Ochocientos", "img": "img/Los números/Ochocientos.jpg", "transcript": "[otʃoˈθjentos]" },
    { "word": "Ochocientos ocho", "img": "img/Los números/Ochocientos ocho.jpg", "transcript": "[otʃoˈθjentos ˈotʃo]" },
    { "word": "Ochocientos ochenta y ocho", "img": "img/Los números/Ochocientos ochenta y ocho.jpg", "transcript": "[otʃoˈθjentos oˈtʃenta i ˈotʃo]" },
    { "word": "Novecientos", "img": "img/Los números/Novecientos.jpg", "transcript": "[noβeˈθjentos]" },
    { "word": "Novecientos nueve", "img": "img/Los números/Novecientos nueve.jpg", "transcript": "[noβeˈθjentos ˈnweβe]" },
    { "word": "Novecientos noventa y nueve", "img": "img/Los números/Novecientos noventa y nueve.jpg", "transcript": "[noβeˈθjentos noˈβenta i ˈnweβe]" },
    { "word": "Mil", "img": "img/Los números/Mil.jpg", "transcript": "[mil]" },
    { "word": "Dos mil", "img": "img/Los números/Dos mil.jpg", "transcript": "[dos mil]" },
    { "word": "Tres mil", "img": "img/Los números/Tres mil.jpg", "transcript": "[tɾes mil]" },
    { "word": "Cuatro mil", "img": "img/Los números/Cuatro mil.jpg", "transcript": "[kwatɾo mil]" },
    { "word": "Cinco mil", "img": "img/Los números/Cinco mil.jpg", "transcript": "[ˈθinko mil]" },
    { "word": "Seis mil", "img": "img/Los números/Seis mil.jpg", "transcript": "[sejs mil]" },
    { "word": "Siete mil", "img": "img/Los números/Siete mil.jpg", "transcript": "[ˈsjete mil]" },
    { "word": "Ocho mil", "img": "img/Los números/Ocho mil.jpg", "transcript": "[ˈotʃo mil]" },
    { "word": "Nueve mil", "img": "img/Los números/Nueve mil.jpg", "transcript": "[ˈnweβe mil]" },
    { "word": "Diez mil", "img": "img/Los números/Diez mil.jpg", "transcript": "[djes mil]" },
    { "word": "Un millón", "img": "img/Los números/Un millón.jpg", "transcript": "[un miˈʎon]" }
  ]
},
{
  "id": "voc-material-escolar",
  "name": "El material escolar",
  "emoji": "✏️",
  "words": [
    { "word": "El lápiz", "img": "img/El material escolar/El lápiz.jpg", "transcript": "[el ˈlapiθ]" },
    { "word": "El bolígrafo", "img": "img/El material escolar/El bolígrafo.jpg", "transcript": "[el boˈliɣɾafo]" },
    { "word": "El rotulador", "img": "img/El material escolar/El rotulador.jpg", "transcript": "[el ro.tu.laˈðoɾ]" },
    { "word": "El sacapuntas", "img": "img/El material escolar/El sacapuntas.jpg", "transcript": "[el sakaˈpuntas]" },
    { "word": "La goma de borrar", "img": "img/El material escolar/La goma de borrar.jpg", "transcript": "[la ˈɡoma de boˈraɾ]" },
    { "word": "Las tijeras", "img": "img/El material escolar/Las tijeras.jpg", "transcript": "[las tiˈxeɾas]" },
    { "word": "La calculadora", "img": "img/El material escolar/La calculadora.jpg", "transcript": "[la kal.kulaˈðoɾa]" },
    { "word": "La regla", "img": "img/El material escolar/La regla.jpg", "transcript": "[la ˈreɣla]" },
    { "word": "El libro", "img": "img/El material escolar/El libro.jpg", "transcript": "[el ˈliβɾo]" },
    { "word": "El estuche", "img": "img/El material escolar/El estuche.jpg", "transcript": "[el esˈtuʧe]" },
    { "word": "El ordenador", "img": "img/El material escolar/El ordenador.jpg", "transcript": "[el oɾðenaˈðoɾ]" },
    { "word": "El portátil", "img": "img/El material escolar/El portátil.jpg", "transcript": "[el poɾtaˈtil]" },
    { "word": "La pizarra", "img": "img/El material escolar/La pizarra.jpg", "transcript": "[la piˈθaɾa]" },
    { "word": "El cuaderno", "img": "img/El material escolar/El cuaderno.jpg", "transcript": "[el kwaˈðeɾno]" },
    { "word": "El clip", "img": "img/El material escolar/El clip.jpg", "transcript": "[el klip]" },
    { "word": "El pegamento", "img": "img/El material escolar/El pegamento.jpg", "transcript": "[el peɣaˈmento]" },
    { "word": "La agenda", "img": "img/El material escolar/La agenda.jpg", "transcript": "[la aˈxenda]" },
    { "word": "La mochila", "img": "img/El material escolar/La mochila.jpg", "transcript": "[la moˈʧila]" },
    { "word": "El globo terráqueo", "img": "img/El material escolar/El globo terráqueo.jpg", "transcript": "[el ˈɡloβo teˈra.keo]" },
    { "word": "El celo", "img": "img/El material escolar/El celo.jpg", "transcript": "[el ˈθelo]" },
    { "word": "La grapadora", "img": "img/El material escolar/La grapadora.jpg", "transcript": "[la ɡɾapaˈðoɾa]" },
    { "word": "Las grapas", "img": "img/El material escolar/Las grapas.jpg", "transcript": "[las ˈɡɾapas]" },
    { "word": "La tiza", "img": "img/El material escolar/La tiza.jpg", "transcript": "[la ˈθiθa]" },
    { "word": "Las ceras de colores", "img": "img/El material escolar/Las ceras de colores.jpg", "transcript": "[las ˈθeɾas de koˈloɾes]" },
    { "word": "Los lápices de colores", "img": "img/El material escolar/Los lápices de colores.jpg", "transcript": "[los ˈlapiθes de koˈloɾes]" },
    { "word": "El bloc", "img": "img/El material escolar/El bloc.jpg", "transcript": "[el ˈblok]" },
    { "word": "Las pinturas", "img": "img/El material escolar/Las pinturas.jpg", "transcript": "[las pinˈtuɾas]" },
    { "word": "El pincel", "img": "img/El material escolar/El pincel.jpg", "transcript": "[el pinˈθel]" },
    { "word": "El álbum de dibujo", "img": "img/El material escolar/El álbum de dibujo.jpg", "transcript": "[el ˈalβum de diˈβuχo]" }
  ]
},
{
  "id": "voc-semana",
  "name": "Días de la semana",
  "emoji": "📅",
  "words": [
    { "word": "El lunes", "img": "img/Días de la semana/El lunes.jpg", "transcript": "[el ˈluneθ]" },
    { "word": "El martes", "img": "img/Días de la semana/El martes.jpg", "transcript": "[el ˈmaɾteθ]" },
    { "word": "El miércoles", "img": "img/Días de la semana/El miércoles.jpg", "transcript": "[el ˈmjɛɾkoles]" },
    { "word": "El jueves", "img": "img/Días de la semana/El jueves.jpg", "transcript": "[el ˈxweβes]" },
    { "word": "El viernes", "img": "img/Días de la semana/El viernes.jpg", "transcript": "[el ˈβjeɾnes]" },
    { "word": "El sábado", "img": "img/Días de la semana/El sábado.jpg", "transcript": "[el ˈsaβaðo]" }
  ]
}
];