const items = [
  { id: "voc-ropa", name: "La ropa", emoji: "👕", words: [
      { word: "El abrigo", img: "img/La ropa/El abrigo.jpg" },
      { word: "El jersey", img: "img/La ropa/El jersey.jpg" },
      { word: "El traje", img: "img/La ropa/El traje.jpg" },
      { word: "La camisa", img: "img/La ropa/La camisa.jpg" },
      { word: "El vestido", img: "img/La ropa/El vestido.jpg" },
      { word: "La camiseta", img: "img/La ropa/La camiseta.jpg" },
      { word: "La chaqueta", img: "img/La ropa/La chaqueta.jpg" },
      { word: "La pijama", img: "img/La ropa/La pijama.jpg" },
      { word: "La falda", img: "img/La ropa/La falda.jpg" },
      { word: "Los pantalones cortos", img: "img/La ropa/Los pantalones cortos.jpg" },
      { word: "Las vaqueros", img: "img/La ropa/Las vaqueros.jpg" },
      { word: "Los pantalones", img: "img/La ropa/Los pantalones.jpg" }
    ]},
  { id: "voc-frutas", name: "Las frutas", emoji: "🍎", words: [
      { word: "Las frutas", img: "img/Las frutas/Las frutas.jpg" },
      { word: "La uva", img: "img/Las frutas/La uva.jpg" },
      { word: "La pera", img: "img/Las frutas/La pera.jpg" },
      { word: "La granada", img: "img/Las frutas/La granada.jpg" },
      { word: "La ciruela", img: "img/Las frutas/La ciruela.jpg" },
      { word: "El plátano", img: "img/Las frutas/El plátano.jpg" },
      { word: "El coco", img: "img/Las frutas/El coco.jpg" },
      { word: "El albaricoque", img: "img/Las frutas/El albaricoque.jpg" },
      { word: "La piña", img: "img/Las frutas/La piña.jpg" },
      { word: "El caqui", img: "img/Las frutas/El caqui.jpg" },
      { word: "El kiwi", img: "img/Las frutas/El kiwi.jpg" },
      { word: "El limón", img: "img/Las frutas/El limón.jpg" },
      { word: "El mango", img: "img/Las frutas/El mango.jpg" },
      { word: "El melocotón", img: "img/Las frutas/El melocotón.jpg" },
      { word: "El pomelo", img: "img/Las frutas/El pomelo.jpg" },
      { word: "La lima", img: "img/Las frutas/La lima.jpg" },
      { word: "La manzana", img: "img/Las frutas/La manzana.jpg" },
      { word: "La naranja", img: "img/Las frutas/La naranja.jpg" }
      // { word: "", img: "img/.jpg" },
    ]},
  { id: "voc-números", name: "Los números", emoji: "🔢", words: [
      { word: "Cero", img: "img/Los números/Cero.jpg" },
      { word: "Uno", img: "img/Los números/Uno.jpg" },
      { word: "Dos", img: "img/Los números/Dos.jpg" },
      { word: "Tres", img: "img/Los números/Tres.jpg" },
      { word: "Cuatro", img: "img/Los números/Cuatro.jpg" },
      { word: "Cinco", img: "img/Los números/Cinco.jpg" },
      { word: "Seis", img: "img/Los números/Seis.jpg" },
      { word: "Siete", img: "img/Los números/Siete.jpg" },
      { word: "Ocho", img: "img/Los números/Ocho.jpg" },
      { word: "Nueve", img: "img/Los números/Nueve.jpg" },
      { word: "Diez", img: "img/Los números/Diez.jpg" },
      { word: "Once", img: "img/Los números/Once.jpg" },
      { word: "Doce", img: "img/Los números/Doce.jpg" },
      { word: "Trece", img: "img/Los números/Trece.jpg" },
      { word: "Catorce", img: "img/Los números/Catorce.jpg" },
      { word: "Quince", img: "img/Los números/Quince.jpg" },
      { word: "Dieciséis", img: "img/Los números/Dieciséis.jpg" },
      { word: "Diecisiete", img: "img/Los números/Diecisiete.jpg" },
      { word: "Dieciocho", img: "img/Los números/Dieciocho.jpg" },
      { word: "Diecinueve", img: "img/Los números/Diecinueve.jpg" },
      { word: "Veinte", img: "img/Los números/Veinte.jpg" },
      { word: "Veintiuno", img: "img/Los números/Veintiuno.jpg" },
      { word: "Veintidós", img: "img/Los números/Veintidós.jpg" },
      { word: "Veintitrés", img: "img/Los números/Veintitrés.jpg" },
      { word: "Veinticuatro", img: "img/Los números/Veinticuatro.jpg" },
      { word: "Veinticinco", img: "img/Los números/Veinticinco.jpg" },
      { word: "Veintiséis", img: "img/Los números/Veintiséis.jpg" },
      { word: "Veintisiete", img: "img/Los números/Veintisiete.jpg" },
      { word: "Veintiocho", img: "img/Los números/Veintiocho.jpg" },
      { word: "Veintinueve", img: "img/Los números/Veintinueve.jpg" },
      { word: "Treinta", img: "img/Los números/Treinta.jpg" },
      { word: "Treinta y uno", img: "img/Los números/Treinta y uno.jpg" },
      { word: "Treinta y dos", img: "img/Los números/Treinta y dos.jpg" },
      { word: "Treinta y tres", img: "img/Los números/Treinta y tres.jpg" },
      { word: "Treinta y cuatro", img: "img/Los números/Treinta y cuatro.jpg" },
      { word: "Treinta y cinco", img: "img/Los números/Treinta y cinco.jpg" },
      { word: "Treinta y seis", img: "img/Los números/Treinta y seis.jpg" },
      { word: "Treinta y siete", img: "img/Los números/Treinta y siete.jpg" },
      { word: "Treinta y ocho", img: "img/Los números/Treinta y ocho.jpg" },
      { word: "Treinta y nueve", img: "img/Los números/Treinta y nueve.jpg" },
      { word: "Cuarenta", img: "img/Los números/Cuarenta.jpg" },
      // { word: "", img: "img/Los números/.jpg" },
    ]},
];
