const items = [
  { id: "voc-abecedario", name: "El abecedario", emoji: "🔠", words: [
      { word: "a", img: "img/El abecedario/a.jpg" },
      { word: "be", img: "img/El abecedario/be.jpg" },
      { word: "ce", img: "img/El abecedario/ce.jpg" },
      { word: "de", img: "img/El abecedario/de.jpg" },
      { word: "e", img: "img/El abecedario/e.jpg" },
      { word: "efe", img: "img/El abecedario/efe.jpg" },
      { word: "ge", img: "img/El abecedario/ge.jpg" },
      { word: "hache", img: "img/El abecedario/hache.jpg" },
      { word: "i", img: "img/El abecedario/i.jpg" },
      { word: "jota", img: "img/El abecedario/jota.jpg" },
      { word: "ka", img: "img/El abecedario/ka.jpg" },
      { word: "ele", img: "img/El abecedario/ele.jpg" },
      { word: "eme", img: "img/El abecedario/eme.jpg" },
      { word: "ene", img: "img/El abecedario/ene.jpg" },
      { word: "eñe", img: "img/El abecedario/eñe.jpg" },
      { word: "o", img: "img/El abecedario/o.jpg" },
      { word: "pe", img: "img/El abecedario/pe.jpg" },
      { word: "cu", img: "img/El abecedario/cu.jpg" },
      { word: "erre", img: "img/El abecedario/erre.jpg" },
      { word: "ese", img: "img/El abecedario/ese.jpg" },
      { word: "te", img: "img/El abecedario/te.jpg" },
      { word: "u", img: "img/El abecedario/u.jpg" },
      { word: "uve", img: "img/El abecedario/uve.jpg" },
      { word: "uve doble", img: "img/El abecedario/uve doble.jpg" },
      { word: "equis", img: "img/El abecedario/equis.jpg" },
      { word: "igrega", img: "img/El abecedario/igrega.jpg" },
      { word: "zeta", img: "img/El abecedario/zeta.jpg" },
      { word: "che", img: "img/El abecedario/che.jpg" },
      { word: "elle", img: "img/El abecedario/elle.jpg" },
    ]},
  { id: "voc-ropa", name: "La ropa", emoji: "👕", words: [
      { word: "El abrigo", img: "img/La ropa/El abrigo.jpg" },
      { word: "El jersey", img: "img/La ropa/El jersey.jpg" },
      { word: "El traje", img: "img/La ropa/El traje.jpg" },
      { word: "La camisa", img: "img/La ropa/La camisa.jpg" },
      { word: "El vestido", img: "img/La ropa/El vestido.jpg" },
      { word: "La camiseta", img: "img/La ropa/La camiseta.jpg" },
      { word: "La chaqueta", img: "img/La ropa/La chaqueta.jpg" },
      { word: "La pijama", img: "img/La ropa/La pijama.jpg" },
      { word: "La falda", img: "img/La ropa/La falda.jpg" },
      { word: "Los pantalones cortos", img: "img/La ropa/Los pantalones cortos.jpg" },
      { word: "Los vaqueros", img: "img/La ropa/Los vaqueros.jpg" },
      { word: "Los pantalones", img: "img/La ropa/Los pantalones.jpg" }
    ]},
  { id: "voc-frutas-1", name: "Las frutas", emoji: "🍎", words: [
      { word: "Las frutas", img: "img/Las frutas/Las frutas.jpg" },
      { word: "La uva", img: "img/Las frutas/La uva.jpg" },
      { word: "La pera", img: "img/Las frutas/La pera.jpg" },
      { word: "La granada", img: "img/Las frutas/La granada.jpg" },
      { word: "La ciruela", img: "img/Las frutas/La ciruela.jpg" },
      { word: "El plátano", img: "img/Las frutas/El plátano.jpg" },
      { word: "El coco", img: "img/Las frutas/El coco.jpg" },
      { word: "El albaricoque", img: "img/Las frutas/El albaricoque.jpg" },
      { word: "La piña", img: "img/Las frutas/La piña.jpg" },
      { word: "El caqui", img: "img/Las frutas/El caqui.jpg" },
      { word: "El kiwi", img: "img/Las frutas/El kiwi.jpg" },
      { word: "El limón", img: "img/Las frutas/El limón.jpg" },
      { word: "El mango", img: "img/Las frutas/El mango.jpg" },
      { word: "El melocotón", img: "img/Las frutas/El melocotón.jpg" },
      { word: "El pomelo", img: "img/Las frutas/El pomelo.jpg" },
      { word: "La lima", img: "img/Las frutas/La lima.jpg" },
      { word: "La manzana", img: "img/Las frutas/La manzana.jpg" },
      { word: "La naranja", img: "img/Las frutas/La naranja.jpg" }
    ]},
  { id: "voc-números-2", name: "Los números de 0 a 100", emoji: "🔢", words: [
      { word: "Cero", img: "img/Los números/Cero.jpg" },
      { word: "Uno", img: "img/Los números/Uno.jpg" },
      { word: "Dos", img: "img/Los números/Dos.jpg" },
      { word: "Tres", img: "img/Los números/Tres.jpg" },
      { word: "Cuatro", img: "img/Los números/Cuatro.jpg" },
      { word: "Cinco", img: "img/Los números/Cinco.jpg" },
      { word: "Seis", img: "img/Los números/Seis.jpg" },
      { word: "Siete", img: "img/Los números/Siete.jpg" },
      { word: "Ocho", img: "img/Los números/Ocho.jpg" },
      { word: "Nueve", img: "img/Los números/Nueve.jpg" },
      { word: "Diez", img: "img/Los números/Diez.jpg" },
      { word: "Once", img: "img/Los números/Once.jpg" },
      { word: "Doce", img: "img/Los números/Doce.jpg" },
      { word: "Trece", img: "img/Los números/Trece.jpg" },
      { word: "Catorce", img: "img/Los números/Catorce.jpg" },
      { word: "Quince", img: "img/Los números/Quince.jpg" },
      { word: "Dieciséis", img: "img/Los números/Dieciséis.jpg" },
      { word: "Diecisiete", img: "img/Los números/Diecisiete.jpg" },
      { word: "Dieciocho", img: "img/Los números/Dieciocho.jpg" },
      { word: "Diecinueve", img: "img/Los números/Diecinueve.jpg" },
      { word: "Veinte", img: "img/Los números/Veinte.jpg" },
      { word: "Veintiuno", img: "img/Los números/Veintiuno.jpg" },
      { word: "Veintidós", img: "img/Los números/Veintidós.jpg" },
      { word: "Veintitrés", img: "img/Los números/Veintitrés.jpg" },
      { word: "Veinticuatro", img: "img/Los números/Veinticuatro.jpg" },
      { word: "Veinticinco", img: "img/Los números/Veinticinco.jpg" },
      { word: "Veintiséis", img: "img/Los números/Veintiséis.jpg" },
      { word: "Veintisiete", img: "img/Los números/Veintisiete.jpg" },
      { word: "Veintiocho", img: "img/Los números/Veintiocho.jpg" },
      { word: "Veintinueve", img: "img/Los números/Veintinueve.jpg" },
      { word: "Treinta", img: "img/Los números/Treinta.jpg" },
      { word: "Treinta y uno", img: "img/Los números/Treinta y uno.jpg" },
      { word: "Treinta y dos", img: "img/Los números/Treinta y dos.jpg" },
      { word: "Treinta y tres", img: "img/Los números/Treinta y tres.jpg" },
      { word: "Treinta y cuatro", img: "img/Los números/Treinta y cuatro.jpg" },
      { word: "Treinta y cinco", img: "img/Los números/Treinta y cinco.jpg" },
      { word: "Treinta y seis", img: "img/Los números/Treinta y seis.jpg" },
      { word: "Treinta y siete", img: "img/Los números/Treinta y siete.jpg" },
      { word: "Treinta y ocho", img: "img/Los números/Treinta y ocho.jpg" },
      { word: "Treinta y nueve", img: "img/Los números/Treinta y nueve.jpg" },
      { word: "Cuarenta", img: "img/Los números/Cuarenta.jpg" },
      { word: "Cuarenta y uno", img: "img/Los números/Cuarenta y uno.jpg" },
      { word: "Cuarenta y dos", img: "img/Los números/Cuarenta y dos.jpg" },
      { word: "Cuarenta y tres", img: "img/Los números/Cuarenta y tres.jpg" },
      { word: "Cuarenta y cuatro", img: "img/Los números/Cuarenta y cuatro.jpg" },
      { word: "Cuarenta y cinco", img: "img/Los números/Cuarenta y cinco.jpg" },
      { word: "Cuarenta y seis", img: "img/Los números/Cuarenta y seis.jpg" },
      { word: "Cuarenta y siete", img: "img/Los números/Cuarenta y siete.jpg" },
      { word: "Cuarenta y ocho", img: "img/Los números/Cuarenta y ocho.jpg" },
      { word: "Cuarenta y nueve", img: "img/Los números/Cuarenta y nueve.jpg" },
      { word: "Cincuenta", img: "img/Los números/Cincuenta.jpg" },
      { word: "Cincuenta y uno", img: "img/Los números/Cincuenta y uno.jpg" },
      { word: "Cincuenta y dos", img: "img/Los números/Cincuenta y dos.jpg" },
      { word: "Cincuenta y tres", img: "img/Los números/Cincuenta y tres.jpg" },
      { word: "Cincuenta y cuatro", img: "img/Los números/Cincuenta y cuatro.jpg" },
      { word: "Cincuenta y cinco", img: "img/Los números/Cincuenta y cinco.jpg" },
      { word: "Cincuenta y seis", img: "img/Los números/Cincuenta y seis.jpg" },
      { word: "Cincuenta y siete", img: "img/Los números/Cincuenta y siete.jpg" },
      { word: "Cincuenta y ocho", img: "img/Los números/Cincuenta y ocho.jpg" },
      { word: "Cincuenta y nueve", img: "img/Los números/Cincuenta y nueve.jpg" },
      { word: "Sesenta", img: "img/Los números/Sesenta.jpg" },
      { word: "Sesenta y uno", img: "img/Los números/Sesenta y uno.jpg" },
      { word: "Sesenta y dos", img: "img/Los números/Sesenta y dos.jpg" },
      { word: "Sesenta y tres", img: "img/Los números/Sesenta y tres.jpg" },
      { word: "Sesenta y cuatro", img: "img/Los números/Sesenta y cuatro.jpg" },
      { word: "Sesenta y cinco", img: "img/Los números/Sesenta y cinco.jpg" },
      { word: "Sesenta y seis", img: "img/Los números/Sesenta y seis.jpg" },
      { word: "Sesenta y siete", img: "img/Los números/Sesenta y siete.jpg" },
      { word: "Sesenta y ocho", img: "img/Los números/Sesenta y ocho.jpg" },
      { word: "Sesenta y nueve", img: "img/Los números/Sesenta y nueve.jpg" },
      { word: "Setenta", img: "img/Los números/Setenta.jpg" },
      { word: "Setenta y uno", img: "img/Los números/Setenta y uno.jpg" },
      { word: "Setenta y dos", img: "img/Los números/Setenta y dos.jpg" },
      { word: "Setenta y tres", img: "img/Los números/Setenta y tres.jpg" },
      { word: "Setenta y cuatro", img: "img/Los números/Setenta y cuatro.jpg" },
      { word: "Setenta y cinco", img: "img/Los números/Setenta y cinco.jpg" },
      { word: "Setenta y seis", img: "img/Los números/Setenta y seis.jpg" },
      { word: "Setenta y siete", img: "img/Los números/Setenta y siete.jpg" },
      { word: "Setenta y ocho", img: "img/Los números/Setenta y ocho.jpg" },
      { word: "Setenta y nueve", img: "img/Los números/Setenta y nueve.jpg" },
      { word: "Ochenta", img: "img/Los números/Ochenta.jpg" },
      { word: "Ochenta y uno", img: "img/Los números/Ochenta y uno.jpg" },
      { word: "Ochenta y dos", img: "img/Los números/Ochenta y dos.jpg" },
      { word: "Ochenta y tres", img: "img/Los números/Ochenta y tres.jpg" },
      { word: "Ochenta y cuatro", img: "img/Los números/Ochenta y cuatro.jpg" },
      { word: "Ochenta y cinco", img: "img/Los números/Ochenta y cinco.jpg" },
      { word: "Ochenta y seis", img: "img/Los números/Ochenta y seis.jpg" },
      { word: "Ochenta y siete", img: "img/Los números/Ochenta y siete.jpg" },
      { word: "Ochenta y ocho", img: "img/Los números/Ochenta y ocho.jpg" },
      { word: "Ochenta y nueve", img: "img/Los números/Ochenta y nueve.jpg" },
      { word: "Noventa", img: "img/Los números/Noventa.jpg" },
      { word: "Noventa y uno", img: "img/Los números/Noventa y uno.jpg" },
      { word: "Noventa y dos", img: "img/Los números/Noventa y dos.jpg" },
      { word: "Noventa y tres", img: "img/Los números/Noventa y tres.jpg" },
      { word: "Noventa y cuatro", img: "img/Los números/Noventa y cuatro.jpg" },
      { word: "Noventa y cinco", img: "img/Los números/Noventa y cinco.jpg" },
      { word: "Noventa y seis", img: "img/Los números/Noventa y seis.jpg" },
      { word: "Noventa y siete", img: "img/Los números/Noventa y siete.jpg" },
      { word: "Noventa y ocho", img: "img/Los números/Noventa y ocho.jpg" },
      { word: "Noventa y nueve", img: "img/Los números/Noventa y nueve.jpg" },
      { word: "Cien", img: "img/Los números/Cien.jpg" }
    ]},
{ id: "voc-números", name: "Los números desde 100", emoji: "💯", words: [
      { word: "Cien", img: "img/Los números/Cien.jpg" },
      { word: "Ciento uno", img: "img/Los números/Ciento uno.jpg" },
      { word: "Ciento once", img: "img/Los números/Ciento once.jpg" },
      { word: "Doscientos", img: "img/Los números/Doscientos.jpg" },
      { word: "Doscientos dos", img: "img/Los números/Doscientos dos.jpg" },
      { word: "Doscientos veintidós", img: "img/Los números/Doscientos veintidós.jpg" },
      { word: "Trescientos", img: "img/Los números/Trescientos.jpg" },
      { word: "Trescientos tres", img: "img/Los números/Trescientos tres.jpg" },
      { word: "Trescientos treinta y tres", img: "img/Los números/Trescientos treinta y tres.jpg" },
      { word: "Cuatrocientos", img: "img/Los números/Cuatrocientos.jpg" },
      { word: "Cuatrocientos cuatro", img: "img/Los números/Cuatrocientos cuatro.jpg" },
      { word: "Cuatrocientos cuarenta y cuatro", img: "img/Los números/Cuatrocientos cuarenta y cuatro.jpg" },
      { word: "Quinientos", img: "img/Los números/Quinientos.jpg" },
      { word: "Quinientos cinco", img: "img/Los números/Quinientos cinco.jpg" },
      { word: "Quinientos cincuenta y cinco", img: "img/Los números/Quinientos cincuenta y cinco.jpg" },
      { word: "Seiscientos", img: "img/Los números/Seiscientos.jpg" },
      { word: "Seiscientos seis", img: "img/Los números/Seiscientos seis.jpg" },
      { word: "Seiscientos sesenta y seis", img: "img/Los números/Seiscientos sesenta y seis.jpg" },
      { word: "Setecientos", img: "img/Los números/Setecientos.jpg" },
      { word: "Setecientos siete", img: "img/Los números/Setecientos siete.jpg" },
      { word: "Setecientos setenta y siete", img: "img/Los números/Setecientos setenta y siete.jpg" },
      { word: "Ochocientos", img: "img/Los números/Ochocientos.jpg" },
      { word: "Ochocientos ocho", img: "img/Los números/Ochocientos ocho.jpg" },
      { word: "Ochocientos ochenta y ocho", img: "img/Los números/Ochocientos ochenta y ocho.jpg" },
      { word: "Novecientos", img: "img/Los números/Novecientos.jpg" },
      { word: "Novecientos nueve", img: "img/Los números/Novecientos nueve.jpg" },
      { word: "Novecientos noventa y nueve", img: "img/Los números/Novecientos noventa y nueve.jpg" },
      { word: "Mil", img: "img/Los números/Mil.jpg" },
      { word: "Dos mil", img: "img/Los números/Dos mil.jpg" },
      { word: "Tres mil", img: "img/Los números/Tres mil.jpg" },
      { word: "Cuatro mil", img: "img/Los números/Cuatro mil.jpg" },
      { word: "Cinco mil", img: "img/Los números/Cinco mil.jpg" },
      { word: "Seis mil", img: "img/Los números/Seis mil.jpg" },
      { word: "Siete mil", img: "img/Los números/Siete mil.jpg" },
      { word: "Ocho mil", img: "img/Los números/Ocho mil.jpg" },
      { word: "Nueve mil", img: "img/Los números/Nueve mil.jpg" },
      { word: "Diez mil", img: "img/Los números/Diez mil.jpg" },
      { word: "Un millón", img: "img/Los números/Un millón.jpg" },
    ]},
    { id: "voc-material-escolar", name: "El material escolar", emoji: "✏️", words: [
      { word: "El lápiz", img: "img/El material escolar/El lápiz.jpg" },
      { word: "El bolígrafo", img: "img/El material escolar/El bolígrafo.jpg" },
      { word: "El rotulador", img: "img/El material escolar/El rotulador.jpg" },
      { word: "El sacapuntas", img: "img/El material escolar/El sacapuntas.jpg" },
      { word: "La goma de borrar", img: "img/El material escolar/La goma de borrar.jpg" },
      { word: "Las tijeras", img: "img/El material escolar/Las tijeras.jpg" },
      { word: "La calculadora", img: "img/El material escolar/La calculadora.jpg" },
      { word: "La regla", img: "img/El material escolar/La regla.jpg" },
      { word: "El libro", img: "img/El material escolar/El libro.jpg" },
      // { word: "", img: "img/El material escolar/.jpg" },
    ]},
];


